import type { ValidationResult, Validator } from "../validation/validation.js";
import { validationFailure, validationSuccess } from "../validation/validation.js";
import type { EvidencePack, EvidencePackRequest, EvidenceRecord, EvidenceRecordRequest, FeedbackMetricImportRequest, FeedbackMetricSnapshot, PublicationAuthorizationRequest, PublicationDryRunRequest, PublicationKillSwitch, PublicationKillSwitchRequest, PublicationPlan, PublicationReceiptRequest, SourceRegistrationRequest, SourceRegistryEntry } from "./operational-plane.js";

const ID = /^[a-zA-Z0-9@._:-]{1,128}$/u;
const FINGERPRINT = /^[a-f0-9]{64}$/u;
const TIMESTAMP = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u;
const CATEGORIES = ["AUTHORIZED_DATASET", "EDITORIAL", "FORBIDDEN", "OFFICIAL_DOCUMENTATION", "OFFICIAL_SITE", "SECONDARY"] as const;
const DOMAINS = ["FINANCE", "GENERAL", "HEALTH", "LEGAL"] as const;
const EVIDENCE_STATUSES = ["CONTESTED", "INSUFFICIENT", "STALE", "VERIFIED"] as const;
const PLATFORMS = ["instagram", "tiktok"] as const;

export class SourceRegistrationRequestValidator implements Validator<SourceRegistrationRequest> { public validate(value: unknown): ValidationResult<SourceRegistrationRequest> { return sourceRequest(value) ? valid(cast<SourceRegistrationRequest>(value)) : invalid("Source registration request is invalid"); } }
export class EvidenceRecordRequestValidator implements Validator<EvidenceRecordRequest> { public validate(value: unknown): ValidationResult<EvidenceRecordRequest> { return evidenceRequest(value) ? valid(cast<EvidenceRecordRequest>(value)) : invalid("Evidence record request is invalid"); } }
export class EvidencePackRequestValidator implements Validator<EvidencePackRequest> { public validate(value: unknown): ValidationResult<EvidencePackRequest> { return record(value) && keys(value, ["evidenceIds", "packId"]) && identifier(value.packId) && ids(value.evidenceIds, 1, 8) ? valid(cast<EvidencePackRequest>(value)) : invalid("Evidence Pack request is invalid"); } }
export class PublicationDryRunRequestValidator implements Validator<PublicationDryRunRequest> { public validate(value: unknown): ValidationResult<PublicationDryRunRequest> { return record(value) && keys(value, ["accountRef", "contentVersion", "idempotencyKey", "platform", "productionId", "publicationId", "scheduledFor"]) && text(value.accountRef, 3, 180) && identifier(value.productionId) && identifier(value.publicationId) && identifier(value.idempotencyKey) && count(value.contentVersion, 0, 1_000_000) && platform(value.platform) && timestamp(value.scheduledFor) ? valid(cast<PublicationDryRunRequest>(value)) : invalid("Publication dry-run request is invalid"); } }
export class PublicationAuthorizationRequestValidator implements Validator<PublicationAuthorizationRequest> { public validate(value: unknown): ValidationResult<PublicationAuthorizationRequest> { return record(value) && keys(value, ["expectedVersion", "publicationId"]) && identifier(value.publicationId) && count(value.expectedVersion, 0, 1_000_000) ? valid(cast<PublicationAuthorizationRequest>(value)) : invalid("Publication authorization request is invalid"); } }
export class PublicationReceiptRequestValidator implements Validator<PublicationReceiptRequest> { public validate(value: unknown): ValidationResult<PublicationReceiptRequest> { const expected = record(value) && value.platformContentRef === undefined ? ["expectedVersion", "outcome", "publicationId", "receiptFingerprint"] : ["expectedVersion", "outcome", "platformContentRef", "publicationId", "receiptFingerprint"]; return record(value) && keys(value, expected) && identifier(value.publicationId) && count(value.expectedVersion, 0, 1_000_000) && ["FAILED", "SUCCEEDED", "UNCERTAIN"].includes(value.outcome as string) && fingerprint(value.receiptFingerprint) && (value.platformContentRef === undefined || text(value.platformContentRef, 3, 200)) && (value.outcome !== "SUCCEEDED" || typeof value.platformContentRef === "string") ? valid(cast<PublicationReceiptRequest>(value)) : invalid("Publication receipt request is invalid"); } }
export class PublicationKillSwitchRequestValidator implements Validator<PublicationKillSwitchRequest> { public validate(value: unknown): ValidationResult<PublicationKillSwitchRequest> { return record(value) && keys(value, ["enabled", "expectedVersion"]) && typeof value.enabled === "boolean" && count(value.expectedVersion, 0, 1_000_000) ? valid(cast<PublicationKillSwitchRequest>(value)) : invalid("Publication kill-switch request is invalid"); } }
export class FeedbackMetricImportRequestValidator implements Validator<FeedbackMetricImportRequest> { public validate(value: unknown): ValidationResult<FeedbackMetricImportRequest> { const expected = record(value) && value.correctionOfSnapshotId === undefined ? ["conversionAttribution", "metrics", "periodEnd", "periodStart", "publicationId", "publicationReceiptFingerprint", "snapshotFingerprint", "snapshotId"] : ["conversionAttribution", "correctionOfSnapshotId", "metrics", "periodEnd", "periodStart", "publicationId", "publicationReceiptFingerprint", "snapshotFingerprint", "snapshotId"]; return record(value) && keys(value, expected) && identifier(value.publicationId) && identifier(value.snapshotId) && fingerprint(value.publicationReceiptFingerprint) && fingerprint(value.snapshotFingerprint) && timestamp(value.periodStart) && timestamp(value.periodEnd) && Date.parse(value.periodStart) <= Date.parse(value.periodEnd) && ["NOT_ATTRIBUTED", "VERIFIED"].includes(value.conversionAttribution as string) && (value.correctionOfSnapshotId === undefined || identifier(value.correctionOfSnapshotId)) && metrics(value.metrics) && (value.conversionAttribution === "VERIFIED" || value.metrics.conversions === 0) ? valid(cast<FeedbackMetricImportRequest>(value)) : invalid("Feedback metric import request is invalid"); } }

export class SourceRegistryEntryValidator implements Validator<SourceRegistryEntry> { public validate(value: unknown): ValidationResult<SourceRegistryEntry> { return record(value) && keys(value, ["actorId", "canonicalReference", "category", "createdAt", "maxFreshnessDays", "name", "permittedRiskDomains", "publicCitationAllowed", "reliability", "requiresSecondSource", "sourceId", "status", "version", "workspaceId"]) && identifier(value.actorId) && identifier(value.workspaceId) && identifier(value.sourceId) && text(value.canonicalReference, 8, 500) && text(value.name, 3, 180) && CATEGORIES.includes(value.category as never) && ["AUTHORIZED", "FORBIDDEN"].includes(value.status as string) && ((value.category === "FORBIDDEN") === (value.status === "FORBIDDEN")) && ["HIGH", "LOW", "MEDIUM"].includes(value.reliability as string) && domains(value.permittedRiskDomains) && typeof value.publicCitationAllowed === "boolean" && typeof value.requiresSecondSource === "boolean" && count(value.maxFreshnessDays, 1, 3650) && timestamp(value.createdAt) && value.version === 0 ? valid(cast<SourceRegistryEntry>(value)) : invalid("Source registry record is invalid"); } }
export class EvidenceRecordValidator implements Validator<EvidenceRecord> { public validate(value: unknown): ValidationResult<EvidenceRecord> { return record(value) && keys(value, ["acquiredAt", "actorId", "claimMappings", "contentPublishedAt", "corroboratingEvidenceIds", "evidenceId", "excerpt", "fingerprint", "freshnessExpiresAt", "limitations", "riskDomain", "sourceId", "sourceReference", "status", "version", "workspaceId"]) && identifier(value.actorId) && identifier(value.workspaceId) && identifier(value.evidenceId) && identifier(value.sourceId) && timestamp(value.acquiredAt) && timestamp(value.contentPublishedAt) && timestamp(value.freshnessExpiresAt) && Date.parse(value.contentPublishedAt) <= Date.parse(value.acquiredAt) && Date.parse(value.acquiredAt) <= Date.parse(value.freshnessExpiresAt) && fingerprint(value.fingerprint) && text(value.sourceReference, 8, 500) && text(value.excerpt, 8, 1200) && mappings(value.claimMappings) && ids(value.corroboratingEvidenceIds, 0, 4) && strings(value.limitations, 1, 6, 320) && DOMAINS.includes(value.riskDomain as never) && EVIDENCE_STATUSES.includes(value.status as never) && value.version === 0 ? valid(cast<EvidenceRecord>(value)) : invalid("Evidence record is invalid"); } }
export class EvidencePackValidator implements Validator<EvidencePack> { public validate(value: unknown): ValidationResult<EvidencePack> { return record(value) && keys(value, ["actorId", "createdAt", "evidence", "evidenceIds", "fingerprint", "minFreshnessExpiresAt", "packId", "status", "version", "workspaceId"]) && identifier(value.actorId) && identifier(value.workspaceId) && identifier(value.packId) && timestamp(value.createdAt) && timestamp(value.minFreshnessExpiresAt) && fingerprint(value.fingerprint) && ids(value.evidenceIds, 1, 8) && evidencePackItems(value.evidence, value.evidenceIds) && value.status === "READY" && value.version === 0 ? valid(cast<EvidencePack>(value)) : invalid("Evidence Pack is invalid"); } }
export class PublicationPlanValidator implements Validator<PublicationPlan> { public validate(value: unknown): ValidationResult<PublicationPlan> { const expected = record(value) ? ["accountRef", "actorId", "contentPackageFingerprint", "contentVersion", "createdAt", "dryRun", "idempotencyKey", "platform", "productionId", "publicationId", "scheduledFor", "status", "updatedAt", "version", "workspaceId", ...(value.authorization === undefined ? [] : ["authorization"]), ...(value.receipt === undefined ? [] : ["receipt"])] : []; return record(value) && keys(value, expected) && identifier(value.actorId) && identifier(value.workspaceId) && identifier(value.productionId) && identifier(value.publicationId) && identifier(value.idempotencyKey) && text(value.accountRef, 3, 180) && fingerprint(value.contentPackageFingerprint) && count(value.contentVersion, 0, 1_000_000) && timestamp(value.createdAt) && timestamp(value.updatedAt) && timestamp(value.scheduledFor) && Date.parse(value.updatedAt) >= Date.parse(value.createdAt) && value.dryRun === true && platform(value.platform) && ["AUTHORIZED", "CANCELLED", "DRY_RUN", "FAILED", "SUCCEEDED", "UNCERTAIN"].includes(value.status as string) && count(value.version, 0, 1_000_000) && publicationShape(value) ? valid(cast<PublicationPlan>(value)) : invalid("Publication plan is invalid"); } }
export class PublicationKillSwitchValidator implements Validator<PublicationKillSwitch> { public validate(value: unknown): ValidationResult<PublicationKillSwitch> { return record(value) && keys(value, ["enabled", "updatedAt", "updatedBy", "version", "workspaceId"]) && typeof value.enabled === "boolean" && identifier(value.updatedBy) && identifier(value.workspaceId) && timestamp(value.updatedAt) && count(value.version, 1, 1_000_000) ? valid(cast<PublicationKillSwitch>(value)) : invalid("Publication kill-switch record is invalid"); } }
export class FeedbackMetricSnapshotValidator implements Validator<FeedbackMetricSnapshot> { public validate(value: unknown): ValidationResult<FeedbackMetricSnapshot> { const expected = record(value) && value.correctionOfSnapshotId === undefined ? ["actorId", "capturedAt", "conversionAttribution", "metrics", "periodEnd", "periodStart", "platform", "productionId", "publicationId", "publicationReceiptFingerprint", "snapshotFingerprint", "snapshotId", "workspaceId"] : ["actorId", "capturedAt", "conversionAttribution", "correctionOfSnapshotId", "metrics", "periodEnd", "periodStart", "platform", "productionId", "publicationId", "publicationReceiptFingerprint", "snapshotFingerprint", "snapshotId", "workspaceId"]; return record(value) && keys(value, expected) && identifier(value.actorId) && identifier(value.workspaceId) && identifier(value.snapshotId) && identifier(value.productionId) && identifier(value.publicationId) && timestamp(value.capturedAt) && timestamp(value.periodStart) && timestamp(value.periodEnd) && Date.parse(value.periodStart) <= Date.parse(value.periodEnd) && platform(value.platform) && fingerprint(value.publicationReceiptFingerprint) && fingerprint(value.snapshotFingerprint) && (value.correctionOfSnapshotId === undefined || identifier(value.correctionOfSnapshotId)) && ["NOT_ATTRIBUTED", "VERIFIED"].includes(value.conversionAttribution as string) && metrics(value.metrics) && (value.conversionAttribution === "VERIFIED" || value.metrics.conversions === 0) ? valid(cast<FeedbackMetricSnapshot>(value)) : invalid("Feedback metric snapshot is invalid"); } }

function sourceRequest(value: unknown): value is Record<string, unknown> { return record(value) && keys(value, ["canonicalReference", "category", "maxFreshnessDays", "name", "permittedRiskDomains", "publicCitationAllowed", "reliability", "requiresSecondSource", "sourceId", "status"]) && identifier(value.sourceId) && text(value.canonicalReference, 8, 500) && text(value.name, 3, 180) && CATEGORIES.includes(value.category as never) && ["AUTHORIZED", "FORBIDDEN"].includes(value.status as string) && ((value.category === "FORBIDDEN") === (value.status === "FORBIDDEN")) && ["HIGH", "LOW", "MEDIUM"].includes(value.reliability as string) && domains(value.permittedRiskDomains) && typeof value.publicCitationAllowed === "boolean" && typeof value.requiresSecondSource === "boolean" && count(value.maxFreshnessDays, 1, 3650); }
function evidenceRequest(value: unknown): value is Record<string, unknown> { return record(value) && keys(value, ["claimMappings", "contentPublishedAt", "corroboratingEvidenceIds", "evidenceId", "excerpt", "fingerprint", "freshnessExpiresAt", "limitations", "riskDomain", "sourceId", "sourceReference", "status"]) && identifier(value.evidenceId) && identifier(value.sourceId) && timestamp(value.contentPublishedAt) && timestamp(value.freshnessExpiresAt) && fingerprint(value.fingerprint) && text(value.sourceReference, 8, 500) && text(value.excerpt, 8, 1200) && mappings(value.claimMappings) && ids(value.corroboratingEvidenceIds, 0, 4) && strings(value.limitations, 1, 6, 320) && DOMAINS.includes(value.riskDomain as never) && EVIDENCE_STATUSES.includes(value.status as never); }
function evidencePackItems(value: unknown, evidenceIds: readonly unknown[]): boolean { return Array.isArray(value) && value.length === evidenceIds.length && value.every((entry, index) => record(entry) && keys(entry, ["acquiredAt", "claimMappings", "contentPublishedAt", "evidenceFingerprint", "evidenceId", "excerpt", "freshnessExpiresAt", "limitations", "riskDomain", "source", "sourceReference"]) && entry.evidenceId === evidenceIds[index] && identifier(entry.evidenceId) && timestamp(entry.acquiredAt) && timestamp(entry.contentPublishedAt) && timestamp(entry.freshnessExpiresAt) && Date.parse(entry.contentPublishedAt) <= Date.parse(entry.acquiredAt) && Date.parse(entry.acquiredAt) <= Date.parse(entry.freshnessExpiresAt) && fingerprint(entry.evidenceFingerprint) && text(entry.excerpt, 8, 1200) && text(entry.sourceReference, 8, 500) && mappings(entry.claimMappings) && strings(entry.limitations, 1, 6, 320) && DOMAINS.includes(entry.riskDomain as never) && record(entry.source) && keys(entry.source, ["canonicalReference", "name", "reliability", "sourceId"]) && identifier(entry.source.sourceId) && text(entry.source.name, 3, 180) && text(entry.source.canonicalReference, 8, 500) && ["HIGH", "LOW", "MEDIUM"].includes(entry.source.reliability as string)); }
function publicationShape(value: Record<string, unknown>): boolean { const authorization = value.authorization; const receipt = value.receipt; if (authorization !== undefined && (!record(authorization) || !keys(authorization, ["authorizedAt", "authorizedBy"]) || !timestamp(authorization.authorizedAt) || !identifier(authorization.authorizedBy))) return false; if (receipt !== undefined) { if (!record(receipt)) return false; const expected = receipt.platformContentRef === undefined ? ["outcome", "receiptFingerprint", "recordedAt"] : ["outcome", "platformContentRef", "receiptFingerprint", "recordedAt"]; if (!keys(receipt, expected) || !["FAILED", "SUCCEEDED", "UNCERTAIN"].includes(receipt.outcome as string) || !fingerprint(receipt.receiptFingerprint) || !timestamp(receipt.recordedAt) || (receipt.platformContentRef !== undefined && !text(receipt.platformContentRef, 3, 200)) || (receipt.outcome === "SUCCEEDED" && receipt.platformContentRef === undefined)) return false; }
  const status = value.status; return (status === "DRY_RUN" && authorization === undefined && receipt === undefined && value.version === 0) || (status === "AUTHORIZED" && authorization !== undefined && receipt === undefined) || (["FAILED", "SUCCEEDED", "UNCERTAIN"].includes(status as string) && authorization !== undefined && receipt !== undefined && record(receipt) && receipt.outcome === status) || (status === "CANCELLED" && authorization === undefined && receipt === undefined);
}
function mappings(value: unknown): boolean { return Array.isArray(value) && value.length >= 1 && value.length <= 8 && value.every((entry) => record(entry) && keys(entry, ["claimId", "statement"]) && identifier(entry.claimId) && text(entry.statement, 8, 500)); }
function metrics(value: unknown): value is Record<string, number> { return record(value) && keys(value, ["clicks", "comments", "completionCount", "conversions", "leadCount", "profileVisits", "saves", "shares", "views", "watchTimeSeconds"]) && Object.values(value).every((entry) => count(entry, 0, 2_000_000_000)); }
function domains(value: unknown): boolean { return Array.isArray(value) && value.length >= 1 && value.length <= 4 && value.every((entry) => DOMAINS.includes(entry as never)) && new Set(value).size === value.length; }
function ids(value: unknown, min: number, max: number): value is readonly string[] { return Array.isArray(value) && value.length >= min && value.length <= max && value.every(identifier) && new Set(value).size === value.length; }
function strings(value: unknown, min: number, max: number, maxLength: number): boolean { return Array.isArray(value) && value.length >= min && value.length <= max && value.every((entry) => text(entry, 1, maxLength)); }
function platform(value: unknown): boolean { return PLATFORMS.includes(value as never); }
function identifier(value: unknown): value is string { return typeof value === "string" && ID.test(value); }
function fingerprint(value: unknown): value is string { return typeof value === "string" && FINGERPRINT.test(value); }
function timestamp(value: unknown): value is string { return typeof value === "string" && TIMESTAMP.test(value) && Number.isFinite(Date.parse(value)); }
function count(value: unknown, min: number, max: number): value is number { return typeof value === "number" && Number.isSafeInteger(value) && value >= min && value <= max; }
function text(value: unknown, min: number, max: number): value is string { return typeof value === "string" && value.trim().length >= min && value.length <= max; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function keys(value: Record<string, unknown>, expected: readonly string[]): boolean { return Object.keys(value).length === expected.length && Object.keys(value).every((key) => expected.includes(key)); }
function valid<T>(value: T): ValidationResult<T> { return validationSuccess(value); }
function invalid<T>(message: string): ValidationResult<T> { return validationFailure([{ code: "invalid_value", message, path: "$" }]); }
function cast<T>(value: T extends never ? never : unknown): T { return value as T; }
