import { createHash } from "node:crypto";

import {
  METODO_VELOCE_SOCIAL_INTELLIGENCE_CONTRACT_VERSION,
  SOCIAL_OPPORTUNITY_CRITERIA,
  type MetodoVeloceSocialIntelligenceRequest,
  type SocialDataKind,
  type SocialPublishingPack,
  type SocialSignalProvenance,
} from "./metodo-veloce-social-intelligence.js";
import { validationFailure, validationSuccess, type ValidationResult, type Validator } from "../validation/validation.js";

const ID = /^[a-zA-Z0-9@._:-]{1,128}$/u;
const TAG = /^#[\p{L}\p{N}_]{2,50}$/u;
const UNSAFE = /(?:\bsk-[A-Za-z0-9_-]{8,}|secret|token|password|raw prompt|raw completion|provider payload|stack trace)/iu;
const BRAND_COMPONENTS = Object.freeze(["CTA", "FONT", "LOGO", "PALETTE", "STRUCTURE", "TONE", "VISUAL_DIRECTION"] as const);
const SEQUENCE_ROLES = Object.freeze(["PROBLEMA", "ERRORI", "METODO", "CASO_PRATICO", "CHECKLIST", "CTA_OFFERTA"] as const);
const SNAPSHOT_WINDOWS = Object.freeze(["30M", "2H", "24H", "72H", "7D"] as const);

export class MetodoVeloceSocialIntelligenceRequestValidator implements Validator<MetodoVeloceSocialIntelligenceRequest> {
  public validate(value: unknown): ValidationResult<MetodoVeloceSocialIntelligenceRequest> {
    if (!record(value) || !exactKeys(value, ["audienceSignals", "audioCandidates", "brandChecks", "competitorSignals", "contractVersion", "conversionIntent", "criterionInputs", "culturalRisks", "hashtagCandidates", "mode", "observedAt", "platforms", "portfolioRole", "productionId", "recentContents", "scheduling", "topic", ...(value.trend === undefined ? [] : ["trend"])]) || value.contractVersion !== METODO_VELOCE_SOCIAL_INTELLIGENCE_CONTRACT_VERSION || !id(value.productionId) || !timestamp(value.observedAt) || !text(value.topic, 4, 300) || !["EVERGREEN", "TREND_REACTIVE"].includes(String(value.mode)) || !["AUTHORITY", "COMMUNITY", "CONVERSION", "DISCOVERY", "RETENTION"].includes(String(value.portfolioRole)) || !platforms(value.platforms) || !criteria(value.criterionInputs) || !audience(value.audienceSignals) || !competitors(value.competitorSignals) || !hashtags(value.hashtagCandidates) || !audio(value.audioCandidates) || !scheduling(value.scheduling) || !recent(value.recentContents) || !brand(value.brandChecks) || !conversion(value.conversionIntent) || !risks(value.culturalRisks) || !trend(value.trend)) return invalid("Metodo Veloce Social Intelligence request is invalid");
    if ((value.mode === "TREND_REACTIVE") !== (value.trend !== undefined)) return invalid("Trend-reactive Social Intelligence requires one declared trend");
    return valid(value as unknown as MetodoVeloceSocialIntelligenceRequest);
  }
}

export class SocialPublishingPackValidator implements Validator<SocialPublishingPack> {
  public validate(value: unknown): ValidationResult<SocialPublishingPack> {
    if (!record(value) || !exactKeys(value, ["abTest", "approvalScope", "audienceDemand", "audioPlan", "blockingReasons", "brandDistinctiveness", "carousel", "competitorGap", "contractVersion", "conversionIntent", "culturalRisk", "decision", "externalActionsAllowed", "fatigue", "fingerprint", "generatedAt", "hashtagSets", "masterContentPack", "measurement", "opportunity", "portfolioRole", "productionId", "publicationWindows", "sequence", "socialSeo", "status", "trendAnalysis", "visualDirection"]) || value.contractVersion !== METODO_VELOCE_SOCIAL_INTELLIGENCE_CONTRACT_VERSION || value.externalActionsAllowed !== false || !id(value.productionId) || !timestamp(value.generatedAt) || !hash(value.fingerprint) || !["BLOCKED", "READY_FOR_FABIO_APPROVAL", "REQUIRES_RESEARCH"].includes(String(value.status)) || !["CALENDARIO", "ENTRO_24_ORE", "PRODURRE_ORA", "RICHIEDE_RICERCA", "SCARTARE"].includes(String(value.decision)) || !strings(value.blockingReasons, 0, 30, 1_000) || !packOpportunity(value.opportunity) || !packCarousel(value.carousel) || !packTrend(value.trendAnalysis) || !packAudience(value.audienceDemand) || !packCompetitor(value.competitorGap) || !packHashtags(value.hashtagSets) || !packAudio(value.audioPlan) || !packApprovalScope(value.approvalScope) || !packMasterContent(value.masterContentPack) || !packWindows(value.publicationWindows) || !packFatigue(value.fatigue) || !packBrand(value.brandDistinctiveness) || !conversion(value.conversionIntent) || !packRisk(value.culturalRisk) || !packSequence(value.sequence) || !packSeo(value.socialSeo) || !packAbTest(value.abTest) || !packMeasurement(value.measurement) || !packVisual(value.visualDirection)) return invalid("Social Publishing Pack is invalid");
    if ((value.status === "BLOCKED") !== (value.blockingReasons.length > 0) || (value.status === "BLOCKED" && !["SCARTARE"].includes(String(value.decision))) || (value.status === "REQUIRES_RESEARCH" && value.decision !== "RICHIEDE_RICERCA") || (value.status === "READY_FOR_FABIO_APPROVAL" && ["RICHIEDE_RICERCA", "SCARTARE"].includes(String(value.decision)))) return invalid("Social Publishing Pack decision state is inconsistent");
    if (socialPublishingPackFingerprint(value as unknown as SocialPublishingPack) !== value.fingerprint) return invalid("Social Publishing Pack fingerprint is invalid");
    return valid(value as unknown as SocialPublishingPack);
  }
}

export function socialPublishingPackFingerprint(value: Omit<SocialPublishingPack, "fingerprint"> | SocialPublishingPack): string {
  const payload: Record<string, unknown> = structuredClone(value as unknown as Record<string, unknown>);
  delete payload.fingerprint;
  return createHash("sha256").update(JSON.stringify(payload), "utf8").digest("hex");
}

function criteria(value: unknown): boolean {
  if (!Array.isArray(value) || value.length !== SOCIAL_OPPORTUNITY_CRITERIA.length) return false;
  const seen = new Set<string>();
  return value.every((entry) => {
    if (!record(entry) || !SOCIAL_OPPORTUNITY_CRITERIA.includes(entry.criterion as never) || seen.has(String(entry.criterion)) || !provenance(entry) || !exactKeys(entry, ["criterion", "dataKind", "note", "observedAt", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.sourceId === undefined ? [] : ["sourceId"]), ...(entry.value === undefined ? [] : ["value"])])) return false;
    seen.add(String(entry.criterion));
    return entry.dataKind === "MISSING" ? entry.value === undefined : score(entry.value);
  });
}

function audience(value: unknown): boolean { return Array.isArray(value) && value.length <= 30 && value.every((entry) => record(entry) && exactKeys(entry, ["dataKind", "intent", "note", "observedAt", "query", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.sourceId === undefined ? [] : ["sourceId"]), ...(entry.strength === undefined ? [] : ["strength"])]) && provenance(entry) && ["ACQUISTO", "APPRENDIMENTO", "CONFRONTO", "PROBLEMA"].includes(String(entry.intent)) && text(entry.query, 2, 500) && (entry.strength === undefined || score(entry.strength))); }
function competitors(value: unknown): boolean { return Array.isArray(value) && value.length <= 30 && value.every((entry) => record(entry) && exactKeys(entry, ["authorized", "competitorId", "dataKind", "format", "note", "observedAt", "observedGap", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.sourceId === undefined ? [] : ["sourceId"])]) && provenance(entry) && typeof entry.authorized === "boolean" && id(entry.competitorId) && text(entry.format, 2, 120) && text(entry.observedGap, 4, 1_000)); }
function hashtags(value: unknown): boolean { return Array.isArray(value) && value.length <= 60 && value.every((entry) => record(entry) && exactKeys(entry, ["cluster", "dataKind", "note", "observedAt", "relevance", "tag", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.expiresAt === undefined ? [] : ["expiresAt"]), ...(entry.saturation === undefined ? [] : ["saturation"]), ...(entry.sourceId === undefined ? [] : ["sourceId"])]) && provenance(entry) && ["BRAND", "EXPERIMENTAL", "NICHE", "TOPIC"].includes(String(entry.cluster)) && typeof entry.tag === "string" && TAG.test(entry.tag) && score(entry.relevance) && (entry.saturation === undefined || score(entry.saturation)) && (entry.expiresAt === undefined || timestamp(entry.expiresAt))); }
function audio(value: unknown): boolean { return Array.isArray(value) && value.length <= 30 && value.every((entry) => record(entry) && exactKeys(entry, ["accountAvailable", "audioId", "dataKind", "note", "observedAt", "rightsStatus", "title", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.expiresAt === undefined ? [] : ["expiresAt"]), ...(entry.sourceId === undefined ? [] : ["sourceId"])]) && provenance(entry) && typeof entry.accountAvailable === "boolean" && id(entry.audioId) && ["COMMERCIAL_ALLOWED", "NOT_AUTHORIZED", "UNKNOWN"].includes(String(entry.rightsStatus)) && text(entry.title, 1, 300) && (entry.expiresAt === undefined || timestamp(entry.expiresAt))); }
function scheduling(value: unknown): boolean { return record(value) && exactKeys(value, ["audienceSampleCount", "candidateWindows", "historicalPostCount"]) && integer(value.audienceSampleCount, 0, 1_000_000_000) && integer(value.historicalPostCount, 0, 1_000_000) && Array.isArray(value.candidateWindows) && value.candidateWindows.length <= 14 && value.candidateWindows.every((entry) => record(entry) && exactKeys(entry, ["dataKind", "endAt", "label", "note", "observedAt", "startAt", ...(entry.evidenceId === undefined ? [] : ["evidenceId"]), ...(entry.sourceId === undefined ? [] : ["sourceId"])]) && provenance(entry) && timestamp(entry.startAt) && timestamp(entry.endAt) && Date.parse(entry.endAt) > Date.parse(entry.startAt) && text(entry.label, 2, 120)); }
function recent(value: unknown): boolean { return Array.isArray(value) && value.length <= 100 && value.every((entry) => record(entry) && exactKeys(entry, ["format", "hookPattern", "topic", "visualPattern", ...(entry.publishedAt === undefined ? [] : ["publishedAt"])]) && text(entry.format, 2, 120) && text(entry.hookPattern, 2, 300) && text(entry.topic, 2, 300) && text(entry.visualPattern, 2, 300) && (entry.publishedAt === undefined || timestamp(entry.publishedAt))); }
function brand(value: unknown): boolean { return Array.isArray(value) && value.length === BRAND_COMPONENTS.length && new Set(value.map((entry) => record(entry) ? entry.component : undefined)).size === BRAND_COMPONENTS.length && value.every((entry) => record(entry) && exactKeys(entry, ["component", "score"]) && BRAND_COMPONENTS.includes(entry.component as never) && score(entry.score)); }
function conversion(value: unknown): boolean { return record(value) && exactKeys(value, ["commercialStep", "doNext", "feel", "understand"]) && text(value.commercialStep, 3, 1_000) && text(value.doNext, 3, 500) && text(value.feel, 3, 500) && text(value.understand, 3, 1_000); }
function risks(value: unknown): boolean { return Array.isArray(value) && value.length <= 30 && value.every((entry) => record(entry) && exactKeys(entry, ["category", "description", "severity", ...(entry.evidenceId === undefined ? [] : ["evidenceId"])]) && ["AMBIGUOUS_LANGUAGE", "CLAIM", "CULTURAL", "IMAGE", "MEME", "REPUTATION"].includes(String(entry.category)) && ["HIGH", "LOW", "MEDIUM"].includes(String(entry.severity)) && text(entry.description, 4, 1_000) && (entry.evidenceId === undefined || id(entry.evidenceId))); }
function trend(value: unknown): boolean { return value === undefined || (record(value) && exactKeys(value, ["expiresAt", "phrase", "phase", "provenance", "publishBy"]) && timestamp(value.expiresAt) && timestamp(value.publishBy) && Date.parse(value.publishBy) <= Date.parse(value.expiresAt) && text(value.phrase, 2, 300) && ["EMERGENTE", "IN_CALO", "IN_CRESCITA", "NON_CLASSIFICATO", "PICCO", "SATURO", "SCADUTO"].includes(String(value.phase)) && Array.isArray(value.provenance) && value.provenance.length > 0 && value.provenance.length <= 10 && value.provenance.every(provenance)); }

function provenance(value: unknown): value is SocialSignalProvenance {
  if (!record(value) || !["ASSUMPTION", "EVIDENCE", "MEASURED", "MISSING"].includes(String(value.dataKind)) || !timestamp(value.observedAt) || !text(value.note, 1, 1_000) || (value.evidenceId !== undefined && !id(value.evidenceId)) || (value.sourceId !== undefined && !id(value.sourceId))) return false;
  const kind = value.dataKind as SocialDataKind;
  if (kind === "EVIDENCE") return value.evidenceId !== undefined;
  if (kind === "MEASURED") return value.sourceId !== undefined;
  if (kind === "MISSING") return value.evidenceId === undefined && value.sourceId === undefined;
  return true;
}

function packOpportunity(value: unknown): boolean { return record(value) && exactKeys(value, ["completeness", "criteria", ...(value.score === undefined ? [] : ["score"])]) && score(value.completeness) && (value.score === undefined || score(value.score)) && Array.isArray(value.criteria) && value.criteria.length === SOCIAL_OPPORTUNITY_CRITERIA.length && value.criteria.every((entry) => record(entry) && SOCIAL_OPPORTUNITY_CRITERIA.includes(entry.criterion as never) && number(entry.weight, 1, 100) && number(entry.confidenceFactor, 0, 1) && (entry.weightedContribution === undefined || number(entry.weightedContribution, 0, 100))); }
function packCarousel(value: unknown): boolean { return Array.isArray(value) && value.length === 6 && value.every((entry, index) => record(entry) && exactKeys(entry, ["body", "slide", "title"]) && entry.slide === index + 1 && text(entry.title, 3, 100) && text(entry.body, 4, 600)); }
function packTrend(value: unknown): boolean { return record(value) && exactKeys(value, ["phase", "status", ...(value.expiresAt === undefined ? [] : ["expiresAt"]), ...(value.publishBy === undefined ? [] : ["publishBy"])]) && ["EMERGENTE", "IN_CALO", "IN_CRESCITA", "NON_CLASSIFICATO", "PICCO", "SATURO", "SCADUTO", "NESSUN_TREND"].includes(String(value.phase)) && ["ACTIVE", "EXPIRED", "NOT_PROVIDED"].includes(String(value.status)) && (value.expiresAt === undefined || timestamp(value.expiresAt)) && (value.publishBy === undefined || timestamp(value.publishBy)); }
function packAudience(value: unknown): boolean { return record(value) && exactKeys(value, ["intents", "provenance", "status"]) && ["INSUFFICIENT_DATA", "VERIFIED"].includes(String(value.status)) && strings(value.intents, 0, 30, 500) && Array.isArray(value.provenance) && value.provenance.every(provenance); }
function packCompetitor(value: unknown): boolean { return record(value) && exactKeys(value, ["authorizedCompetitors", "gaps", "status"]) && integer(value.authorizedCompetitors, 0, 1_000) && strings(value.gaps, 0, 30, 1_000) && ["INSUFFICIENT_DATA", "VERIFIED"].includes(String(value.status)); }
function packHashtags(value: unknown): boolean { return record(value) && exactKeys(value, ["alternate", "experimental", "main", "status"]) && ["INSUFFICIENT_DATA", "VERIFIED"].includes(String(value.status)) && [value.main, value.alternate, value.experimental].every((set) => Array.isArray(set) && set.length <= 15 && set.every((tag) => typeof tag === "string" && TAG.test(tag))); }
function packAudio(value: unknown): boolean { return record(value) && exactKeys(value, ["status", "unauthorized", ...(value.selected === undefined ? [] : ["selected"])]) && ["AUDIO_AUTORIZZATO", "AUDIO_NON_AUTORIZZATO", "NESSUN_AUDIO_SELEZIONATO"].includes(String(value.status)) && strings(value.unauthorized, 0, 30, 300) && (value.selected === undefined || (record(value.selected) && exactKeys(value.selected, ["audioId", "title"]) && id(value.selected.audioId) && text(value.selected.title, 1, 300))); }
function packApprovalScope(value: unknown): boolean { return record(value) && exactKeys(value, ["consequences", "invalidatedByAnyChange", "publicationAuthorized", "schedulingAuthorized", "scope"]) && value.scope === "INTERNAL_PACKAGE_ONLY" && value.invalidatedByAnyChange === true && value.publicationAuthorized === false && value.schedulingAuthorized === false && strings(value.consequences, 3, 6, 500); }
function packMasterContent(value: unknown): boolean {
  if (!record(value) || !exactKeys(value, ["brandInvariants", "fingerprint", "nativeVariants", "reelIncluded", "reelOmissionReason", "slideCount", "topic"]) || !hash(value.fingerprint) || value.slideCount !== 6 || value.reelIncluded !== false || !text(value.reelOmissionReason, 8, 500) || !text(value.topic, 4, 300) || JSON.stringify(value.brandInvariants) !== JSON.stringify(["TOPIC", "IDENTITY", "LOGO", "MESSAGE", "TYPOGRAPHY", "PALETTE", "CTA"]) || !record(value.nativeVariants) || !exactKeys(value.nativeVariants, ["instagram", "tiktok"]) || !nativeVariant(value.nativeVariants.instagram, "INSTAGRAM", "CAROUSEL", "1080x1350", "4:5") || !nativeVariant(value.nativeVariants.tiktok, "TIKTOK", "SLIDESHOW", "1080x1920", "9:16")) return false;
  const payload = structuredClone(value); delete payload.fingerprint;
  return createHash("sha256").update(JSON.stringify(payload), "utf8").digest("hex") === value.fingerprint;
}
function nativeVariant(value: unknown, platform: "INSTAGRAM" | "TIKTOK", format: "CAROUSEL" | "SLIDESHOW", canvas: "1080x1350" | "1080x1920", aspectRatio: "4:5" | "9:16"): boolean {
  return record(value) && exactKeys(value, ["aspectRatio", "audio", "canvas", "caption", "cta", "format", "hashtagSets", "platform", "publicationWindowLabels", "slides"]) && value.platform === platform && value.format === format && value.canvas === canvas && value.aspectRatio === aspectRatio && text(value.caption, 10, 3_000) && text(value.cta, 3, 500) && packHashtags(value.hashtagSets) && strings(value.publicationWindowLabels, 0, 14, 120) && Array.isArray(value.slides) && value.slides.length === 6 && value.slides.every((slide, index) => record(slide) && exactKeys(slide, ["body", "layoutInstruction", "slide", "title"]) && slide.slide === index + 1 && text(slide.title, 3, 100) && text(slide.body, 4, 600) && text(slide.layoutInstruction, 8, 500)) && record(value.audio) && exactKeys(value.audio, ["fallback", "status"]) && ["AUDIO_ORIGINALE_METODO_VELOCE_O_NESSUN_AUDIO", "NON_APPLICABILE"].includes(String(value.audio.fallback)) && ["AUDIO_AUTORIZZATO", "AUDIO_NON_AUTORIZZATO", "NESSUN_AUDIO_SELEZIONATO", "NON_APPLICABILE"].includes(String(value.audio.status));
}
function packWindows(value: unknown): boolean { return record(value) && exactKeys(value, ["mode", "status", "windows", ...(value.testPlan === undefined ? [] : ["testPlan"])]) && ["DYNAMIC", "EXPERIMENTAL"].includes(String(value.mode)) && ["DATA_SUFFICIENT", "DATI_INSUFFICIENTI"].includes(String(value.status)) && Array.isArray(value.windows) && value.windows.length <= 14 && value.windows.every((entry) => record(entry) && exactKeys(entry, ["endAt", "label", "startAt"]) && timestamp(entry.startAt) && timestamp(entry.endAt) && Date.parse(entry.endAt) > Date.parse(entry.startAt) && text(entry.label, 2, 120)) && (value.testPlan === undefined || text(value.testPlan, 4, 1_000)) && ((value.status === "DATI_INSUFFICIENTI") === (value.mode === "EXPERIMENTAL")); }
function packFatigue(value: unknown): boolean { return record(value) && exactKeys(value, ["repeatedSignals", "score", "status"]) && score(value.score) && strings(value.repeatedSignals, 0, 30, 500) && ["FRESH", "HIGH", "WATCH"].includes(String(value.status)); }
function packBrand(value: unknown): boolean { return record(value) && exactKeys(value, ["score", "status"]) && score(value.score) && ["DISTINCTIVE", "REMEDIATE"].includes(String(value.status)); }
function packRisk(value: unknown): boolean { return record(value) && exactKeys(value, ["findings", "status"]) && ["BLOCKED", "CLEAR"].includes(String(value.status)) && risks(value.findings); }
function packSequence(value: unknown): boolean { return Array.isArray(value) && value.length === 6 && value.every((entry, index) => record(entry) && exactKeys(entry, ["callToAction", "position", "role"]) && entry.position === index + 1 && entry.role === SEQUENCE_ROLES[index] && text(entry.callToAction, 3, 300)); }
function packSeo(value: unknown): boolean { return record(value) && exactKeys(value, ["captionKeywords", "onScreenPhrases", "searchIntent"]) && strings(value.captionKeywords, 1, 12, 100) && strings(value.onScreenPhrases, 1, 12, 150) && text(value.searchIntent, 3, 500); }
function packAbTest(value: unknown): boolean { return record(value) && exactKeys(value, ["control", "hypothesis", "measurementWindow", "primaryMetric", "variable", "variant"]) && value.measurementWindow === "24H" && ["CTA", "HOOK", "VISUAL_OPENING"].includes(String(value.variable)) && text(value.control, 2, 500) && text(value.variant, 2, 500) && text(value.hypothesis, 4, 1_000) && text(value.primaryMetric, 2, 200); }
function packMeasurement(value: unknown): boolean { return record(value) && exactKeys(value, ["nextDecision", "snapshots"]) && text(value.nextDecision, 4, 1_000) && Array.isArray(value.snapshots) && value.snapshots.length === SNAPSHOT_WINDOWS.length && value.snapshots.every((entry, index) => record(entry) && exactKeys(entry, ["metrics", "status", "window"]) && entry.window === SNAPSHOT_WINDOWS[index] && entry.status === "AWAITING_REAL_IMPORT" && strings(entry.metrics, 5, 20, 120)); }
function packVisual(value: unknown): boolean { return record(value) && exactKeys(value, ["aspectRatio", "brandSignature", "canvas", "imageStyle", "palette", "slidePrompts"]) && value.aspectRatio === "4:5" && value.canvas === "1080x1350" && value.imageStyle === "ULTRAREALISTIC_CINEMATIC" && Array.isArray(value.palette) && JSON.stringify(value.palette) === JSON.stringify(["#050505", "#FFD400", "#F7F7F4"]) && text(value.brandSignature, 4, 500) && strings(value.slidePrompts, 6, 6, 1_000); }

function platforms(value: unknown): boolean { return Array.isArray(value) && value.length > 0 && value.length <= 2 && new Set(value).size === value.length && value.every((entry) => ["INSTAGRAM", "TIKTOK"].includes(String(entry))); }
function strings(value: unknown, min: number, max: number, maxLength: number): value is readonly string[] { return Array.isArray(value) && value.length >= min && value.length <= max && value.every((entry) => text(entry, 1, maxLength)); }
function score(value: unknown): value is number { return number(value, 0, 100); }
function integer(value: unknown, min: number, max: number): value is number { return number(value, min, max) && Number.isSafeInteger(value); }
function number(value: unknown, min: number, max: number): value is number { return typeof value === "number" && Number.isFinite(value) && value >= min && value <= max; }
function text(value: unknown, min: number, max: number): value is string { return typeof value === "string" && value.trim().length >= min && value.length <= max && !UNSAFE.test(value); }
function id(value: unknown): value is string { return typeof value === "string" && ID.test(value); }
function hash(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/u.test(value); }
function timestamp(value: unknown): value is string { return typeof value === "string" && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(value) && Number.isFinite(Date.parse(value)); }
function exactKeys(value: Record<string, unknown>, expected: readonly string[]): boolean { const actual = Object.keys(value).sort(); const sorted = [...expected].sort(); return actual.length === sorted.length && actual.every((key, index) => key === sorted[index]); }
function record(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function invalid<T>(message: string): ValidationResult<T> { return validationFailure([{ code: "invalid_value", message, path: "$" }]); }
function valid<T>(value: T): ValidationResult<T> { return validationSuccess(deepFreeze(structuredClone(value))); }
function deepFreeze<T>(value: T): T { if (typeof value !== "object" || value === null || Object.isFrozen(value)) return value; Object.freeze(value); for (const child of Object.values(value)) deepFreeze(child); return value; }
