import { describe, expect, it } from "vitest";
import { FixedClock } from "../support/fixtures.js";
import { DeterministicWorkflowStateMachine, WorkflowCommandValidator, WorkflowDefinitionValidator, WorkflowInstanceValidator, isWorkflowStepTransitionAllowed, isWorkflowTransitionAllowed, type WorkflowCommand, type WorkflowInstance } from "../../src/index.js";

const instance = (): WorkflowInstance => ({ contractVersion:"1",definitionId:"definition@1.0.0",instanceId:"instance-001",status:"ACTIVE",steps:[{stepId:"step-01",status:"AWAITING_RESULT",blockers:[]}],version:0,receipts:[],createdAt:"2026-07-02T10:00:00.000Z",updatedAt:"2026-07-02T10:00:00.000Z",stopReason:"NONE",nonExecuting:true });
const command=(kind:WorkflowCommand["kind"],overrides:Partial<WorkflowCommand>={}):WorkflowCommand=>({commandId:`command-${kind.toLowerCase()}`,expectedVersion:0,kind,reasonCode:"operator-request",nonExecuting:true,...overrides});
describe("Workflow Domain State Machine",()=>{
 it("covers every workflow transition pair with a default-deny matrix",()=>{const statuses=["ACTIVE","PAUSED","COMPLETED","FAILED","CANCELLED"] as const;const allowed:Record<typeof statuses[number],readonly string[]>={ACTIVE:["PAUSED","COMPLETED","FAILED","CANCELLED"],PAUSED:["ACTIVE","CANCELLED"],COMPLETED:[],FAILED:[],CANCELLED:[]};for(const from of statuses)for(const to of statuses)expect(isWorkflowTransitionAllowed(from,to)).toBe(allowed[from].includes(to));});
 it("covers every step transition pair with a default-deny matrix",()=>{const statuses=["PENDING","READY","AWAITING_RESULT","SUCCEEDED","FAILED","CANCELLED"] as const;const allowed:Record<typeof statuses[number],readonly string[]>={PENDING:["READY","CANCELLED"],READY:["AWAITING_RESULT","CANCELLED"],AWAITING_RESULT:["SUCCEEDED","FAILED","CANCELLED"],SUCCEEDED:[],FAILED:[],CANCELLED:[]};for(const from of statuses)for(const to of statuses)expect(isWorkflowStepTransitionAllowed(from,to)).toBe(allowed[from].includes(to));});
 it("accepts only declared workflow and step transitions",()=>{expect(isWorkflowTransitionAllowed("ACTIVE","PAUSED")).toBe(true);expect(isWorkflowTransitionAllowed("ACTIVE","ACTIVE")).toBe(false);expect(isWorkflowStepTransitionAllowed("AWAITING_RESULT","SUCCEEDED")).toBe(true);expect(isWorkflowStepTransitionAllowed("SUCCEEDED","READY")).toBe(false);});
 it("applies, versions, freezes, and replays an identical command",()=>{const m=new DeterministicWorkflowStateMachine(new FixedClock());const first=m.apply(instance(),command("COMPLETE_STEP",{stepId:"step-01"}));const replay=m.apply(first.instance,command("COMPLETE_STEP",{stepId:"step-01"}));expect(first.instance.version).toBe(1);expect(first.instance.status).toBe("COMPLETED");expect(replay.outcome).toBe("REPLAYED");expect(replay.instance.version).toBe(1);expect(Object.isFrozen(first.instance.steps)).toBe(true);});
 it("rejects stale, conflicting, terminal, and duplicate completion commands",()=>{const m=new DeterministicWorkflowStateMachine(new FixedClock());expect(()=>m.apply(instance(),command("PAUSE",{expectedVersion:1}))).toThrow(/stale/);const first=m.apply(instance(),command("COMPLETE_STEP",{stepId:"step-01"}));expect(()=>m.apply(first.instance,command("FAIL_STEP",{commandId:"command-complete_step",expectedVersion:1,stepId:"step-01"}))).toThrow(/conflicts/);expect(()=>m.apply(first.instance,command("PAUSE",{expectedVersion:1}))).toThrow(/terminal/);});
 it("supports pause, resume, cancellation, and failure without execution",()=>{const m=new DeterministicWorkflowStateMachine(new FixedClock());const paused=m.apply(instance(),command("PAUSE")).instance;expect(paused.status).toBe("PAUSED");const resumed=m.apply(paused,command("RESUME",{expectedVersion:1})).instance;expect(resumed.status).toBe("ACTIVE");const cancelled=m.apply(resumed,command("CANCEL",{expectedVersion:2})).instance;expect(cancelled.status).toBe("CANCELLED");expect(cancelled.steps[0]?.status).toBe("CANCELLED");const failed=m.apply(instance(),command("FAIL_STEP",{stepId:"step-01"})).instance;expect(failed.stopReason).toBe("FAILED_STEP");});
 it("validates safe domain contracts and rejects unsafe or duplicate data",()=>{const definition={contractVersion:"1",definitionId:"definition@1.0.0",workflowId:"workflow",workflowVersion:"1.0.0",steps:[{stepId:"step-01",dependencies:[],approvalRequired:false,guardianRequired:false,nonExecuting:true}],nonExecuting:true};expect(new WorkflowDefinitionValidator().validate(definition).ok).toBe(true);expect(new WorkflowDefinitionValidator().validate({...definition,steps:[...definition.steps,{...definition.steps[0]}]}).ok).toBe(false);expect(new WorkflowInstanceValidator().validate(instance()).ok).toBe(true);expect(new WorkflowCommandValidator().validate(command("PAUSE")).ok).toBe(true);const unsafe={...command("PAUSE"),reasonCode:"read sk-private-value"};const result=new WorkflowCommandValidator().validate(unsafe);expect(result.ok).toBe(false);expect(JSON.stringify(result)).not.toContain("sk-private-value");});
});
