import type { DatabaseSync } from "node:sqlite";

import { RepositoryConflictError, RepositoryValidationError } from "../../errors/core-error.js";
import type { EvidenceRecord, FeedbackMetricSnapshot, PublicationKillSwitch, PublicationPlan, SourceRegistryEntry } from "../../operational-planes/operational-plane.js";
import type { OperationalPlaneRepository } from "../../operational-planes/operational-plane-repository.js";
import { EvidenceRecordValidator, FeedbackMetricSnapshotValidator, PublicationKillSwitchValidator, PublicationPlanValidator, SourceRegistryEntryValidator } from "../../operational-planes/operational-plane-validator.js";
import { isPublicationTransitionAllowed } from "../../operational-planes/operational-plane.js";
import { isSqliteConstraintError, SqliteRepositoryError } from "./sqlite-error.js";
import { assertActiveTransaction, type SqliteTransactionScope } from "./sqlite-transaction-scope.js";
import type { ValidationResult, Validator } from "../../validation/validation.js";

export class SqliteOperationalPlaneRepository implements OperationalPlaneRepository {
  readonly #evidence = new EvidenceRecordValidator();
  readonly #feedback = new FeedbackMetricSnapshotValidator();
  readonly #killSwitch = new PublicationKillSwitchValidator();
  readonly #publication = new PublicationPlanValidator();
  readonly #source = new SourceRegistryEntryValidator();
  public constructor(private readonly database: DatabaseSync, private readonly scope: SqliteTransactionScope) {}

  public getSourceById(sourceId: string): Promise<SourceRegistryEntry | undefined> { return Promise.resolve(this.#get("source_registry_entries", "source_id", sourceId, (value) => validationValue(this.#source.validate(value)), "Evidence source")); }
  public getEvidenceById(evidenceId: string): Promise<EvidenceRecord | undefined> { return Promise.resolve(this.#get("evidence_records", "evidence_id", evidenceId, (value) => validationValue(this.#evidence.validate(value)), "Evidence record")); }
  public getPublicationById(publicationId: string): Promise<PublicationPlan | undefined> { return Promise.resolve(this.#get("publication_plans", "publication_id", publicationId, (value) => validationValue(this.#publication.validate(value)), "Publication plan")); }
  public getPublicationKillSwitch(workspaceId: string): Promise<PublicationKillSwitch | undefined> { return Promise.resolve(this.#get("publication_kill_switches", "workspace_id", workspaceId, (value) => validationValue(this.#killSwitch.validate(value)), "Publication kill switch")); }
  public getFeedbackSnapshotById(snapshotId: string): Promise<FeedbackMetricSnapshot | undefined> { return Promise.resolve(this.#get("feedback_metric_snapshots", "snapshot_id", snapshotId, (value) => validationValue(this.#feedback.validate(value)), "Feedback metric snapshot")); }

  public insertSource(record: SourceRegistryEntry): Promise<void> { const checked = this.#checked(record, this.#source, "Evidence source"); return this.#insert("INSERT INTO source_registry_entries (source_id, workspace_id, actor_id, status, category, record_json) VALUES (?, ?, ?, ?, ?, ?)", [checked.sourceId, checked.workspaceId, checked.actorId, checked.status, checked.category, JSON.stringify(checked)], "Evidence source", checked.sourceId); }
  public insertEvidence(record: EvidenceRecord): Promise<void> { const checked = this.#checked(record, this.#evidence, "Evidence record"); return this.#insert("INSERT INTO evidence_records (evidence_id, workspace_id, actor_id, source_id, status, freshness_expires_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?)", [checked.evidenceId, checked.workspaceId, checked.actorId, checked.sourceId, checked.status, checked.freshnessExpiresAt, JSON.stringify(checked)], "Evidence record", checked.evidenceId); }
  public insertPublication(record: PublicationPlan): Promise<void> { const checked = this.#checked(record, this.#publication, "Publication plan"); if (checked.version !== 0 || checked.status !== "DRY_RUN") throw new RepositoryValidationError("A new publication plan must be a dry-run at version zero"); return this.#insert("INSERT INTO publication_plans (publication_id, workspace_id, actor_id, production_id, idempotency_key, status, version, scheduled_for, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [checked.publicationId, checked.workspaceId, checked.actorId, checked.productionId, checked.idempotencyKey, checked.status, checked.version, checked.scheduledFor, checked.updatedAt, JSON.stringify(checked)], "Publication plan", checked.publicationId); }
  public insertFeedbackSnapshot(record: FeedbackMetricSnapshot): Promise<void> { const checked = this.#checked(record, this.#feedback, "Feedback metric snapshot"); return this.#insert("INSERT INTO feedback_metric_snapshots (snapshot_id, workspace_id, actor_id, publication_id, production_id, platform, captured_at, correction_of_snapshot_id, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [checked.snapshotId, checked.workspaceId, checked.actorId, checked.publicationId, checked.productionId, checked.platform, checked.capturedAt, checked.correctionOfSnapshotId ?? null, JSON.stringify(checked)], "Feedback metric snapshot", checked.snapshotId); }

  public updatePublication(record: PublicationPlan, expectation: { readonly version: number }): Promise<void> {
    assertActiveTransaction(this.scope); const checked = this.#checked(record, this.#publication, "Publication plan"); const current = this.#selectPublication(checked.publicationId); if (current === undefined) throw new RepositoryConflictError("Publication plan transition is invalid"); if (current.version !== expectation.version || checked.version !== expectation.version + 1 || !samePublicationIdentity(current, checked) || !isPublicationTransitionAllowed(current.status, checked.status)) throw new RepositoryConflictError("Publication plan transition is invalid");
    const result = this.database.prepare("UPDATE publication_plans SET status = ?, version = ?, updated_at = ?, record_json = ? WHERE publication_id = ? AND version = ?").run(checked.status, checked.version, checked.updatedAt, JSON.stringify(checked), checked.publicationId, expectation.version); if (result.changes !== 1) throw new RepositoryConflictError("Publication plan changed during update"); return Promise.resolve();
  }
  public upsertPublicationKillSwitch(record: PublicationKillSwitch, expectation: { readonly version: number }): Promise<void> {
    assertActiveTransaction(this.scope); const checked = this.#checked(record, this.#killSwitch, "Publication kill switch"); const current = this.#selectKillSwitch(checked.workspaceId); if ((current?.version ?? 0) !== expectation.version || checked.version !== expectation.version + 1) throw new RepositoryConflictError("Publication kill switch changed during update");
    if (current === undefined) { try { this.database.prepare("INSERT INTO publication_kill_switches (workspace_id, enabled, version, updated_at, record_json) VALUES (?, ?, ?, ?, ?)").run(checked.workspaceId, checked.enabled ? 1 : 0, checked.version, checked.updatedAt, JSON.stringify(checked)); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError("Publication kill switch changed during insert"); throw new SqliteRepositoryError("Publication kill switch write failed", "publication_kill_switch.insert"); } }
    else { const result = this.database.prepare("UPDATE publication_kill_switches SET enabled = ?, version = ?, updated_at = ?, record_json = ? WHERE workspace_id = ? AND version = ?").run(checked.enabled ? 1 : 0, checked.version, checked.updatedAt, JSON.stringify(checked), checked.workspaceId, expectation.version); if (result.changes !== 1) throw new RepositoryConflictError("Publication kill switch changed during update"); }
    return Promise.resolve();
  }
  public listFeedbackSnapshots(publicationId: string): Promise<readonly FeedbackMetricSnapshot[]> { assertActiveTransaction(this.scope); assertId(publicationId); const rows = this.database.prepare("SELECT record_json FROM feedback_metric_snapshots WHERE publication_id = ? ORDER BY captured_at ASC, snapshot_id ASC").all(publicationId); return Promise.resolve(Object.freeze(rows.map((row) => this.#decode(row, this.#feedback, "Feedback metric snapshot")))); }

  #get<T>(table: string, key: string, id: string, decode: (value: unknown) => T | undefined, label: string): T | undefined { assertActiveTransaction(this.scope); assertId(id); const row = this.database.prepare(`SELECT record_json FROM ${table} WHERE ${key} = ?`).get(id); if (row === undefined) return undefined; if (typeof row.record_json !== "string") throw new RepositoryValidationError(`${label} is corrupted`); try { const value = decode(JSON.parse(row.record_json)); if (value === undefined) throw new Error("invalid"); return value; } catch { throw new RepositoryValidationError(`${label} is corrupted`); } }
  #insert(statement: string, values: readonly (string | number | null)[], label: string, id: string): Promise<void> { assertActiveTransaction(this.scope); try { this.database.prepare(statement).run(...values); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError(`${label} already exists`, { id }); throw new SqliteRepositoryError(`${label} write failed`, "operational_plane.insert"); } return Promise.resolve(); }
  #selectPublication(id: string): PublicationPlan | undefined { return this.#get("publication_plans", "publication_id", id, (value) => validationValue(this.#publication.validate(value)), "Publication plan"); }
  #selectKillSwitch(workspaceId: string): PublicationKillSwitch | undefined { return this.#get("publication_kill_switches", "workspace_id", workspaceId, (value) => validationValue(this.#killSwitch.validate(value)), "Publication kill switch"); }
  #decode<T>(row: Record<string, unknown>, validator: Validator<T>, label: string): T { if (typeof row.record_json !== "string") throw new RepositoryValidationError(`${label} is corrupted`); try { return this.#checked(JSON.parse(row.record_json), validator, label); } catch { throw new RepositoryValidationError(`${label} is corrupted`); } }
  #checked<T>(value: unknown, validator: Validator<T>, label: string): T { const checked = validator.validate(value); if (!checked.ok) throw new RepositoryValidationError(`${label} is invalid`, { issueCount: checked.issues.length }); return checked.value; }
}

function validationValue<T>(result: ValidationResult<T>): T | undefined { return result.ok ? result.value : undefined; }
function samePublicationIdentity(left: PublicationPlan, right: PublicationPlan): boolean { return left.accountRef === right.accountRef && left.actorId === right.actorId && left.contentPackageFingerprint === right.contentPackageFingerprint && left.contentVersion === right.contentVersion && left.createdAt === right.createdAt && left.idempotencyKey === right.idempotencyKey && left.platform === right.platform && left.productionId === right.productionId && left.publicationId === right.publicationId && left.scheduledFor === right.scheduledFor && left.workspaceId === right.workspaceId; }
function assertId(value: unknown): asserts value is string { if (typeof value !== "string" || !/^[a-zA-Z0-9@._:-]{1,128}$/u.test(value)) throw new RepositoryValidationError("Operational plane ID is invalid"); }
