import type { DatabaseSync } from "node:sqlite";

import type { AuthorizedResearchMission, ResearchAcquisitionSnapshot } from "../../research/authorized-research.js";
import type { AuthorizedResearchRepository } from "../../research/authorized-research-repository.js";
import { AuthorizedResearchMissionValidator, ResearchAcquisitionSnapshotValidator } from "../../research/authorized-research-validator.js";
import { RepositoryConflictError, RepositoryValidationError } from "../../errors/core-error.js";
import { isSqliteConstraintError, SqliteRepositoryError } from "./sqlite-error.js";
import { assertActiveTransaction, type SqliteTransactionScope } from "./sqlite-transaction-scope.js";

export class SqliteAuthorizedResearchRepository implements AuthorizedResearchRepository {
  readonly #mission = new AuthorizedResearchMissionValidator();
  readonly #snapshot = new ResearchAcquisitionSnapshotValidator();
  public constructor(private readonly database: DatabaseSync, private readonly scope: SqliteTransactionScope) {}
  public getMissionById(missionId: string): Promise<AuthorizedResearchMission | undefined> { assertActiveTransaction(this.scope); assertId(missionId); const row = this.database.prepare("SELECT record_json FROM authorized_research_missions WHERE mission_id = ?").get(missionId); return Promise.resolve(row === undefined ? undefined : this.#decodeMission(row)); }
  public getSnapshotById(snapshotId: string): Promise<ResearchAcquisitionSnapshot | undefined> { assertActiveTransaction(this.scope); assertId(snapshotId); const row = this.database.prepare("SELECT record_json FROM research_acquisition_snapshots WHERE snapshot_id = ?").get(snapshotId); return Promise.resolve(row === undefined ? undefined : this.#decodeSnapshot(row)); }
  public insertMission(mission: AuthorizedResearchMission): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#checkedMission(mission); if (checked.version !== 0 || checked.status !== "RUNNING") throw new RepositoryValidationError("A new Authorized Research Mission must be running at version zero"); try { this.database.prepare("INSERT INTO authorized_research_missions (mission_id, workspace_id, actor_id, status, version, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?)").run(checked.input.missionId, checked.workspaceId, checked.actorId, checked.status, checked.version, checked.updatedAt, JSON.stringify(checked)); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError("Authorized Research Mission already exists"); throw new SqliteRepositoryError("Authorized Research Mission write failed", "authorized_research.mission.insert"); } return Promise.resolve(); }
  public insertSnapshot(snapshot: ResearchAcquisitionSnapshot): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#checkedSnapshot(snapshot); try { this.database.prepare("INSERT INTO research_acquisition_snapshots (snapshot_id, mission_id, workspace_id, source_id, evidence_id, acquired_at, fingerprint, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)").run(checked.snapshotId, checked.missionId, checked.workspaceId, checked.sourceId, checked.evidenceId, checked.acquiredAt, checked.fingerprint, JSON.stringify(checked)); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError("Authorized Research snapshot already exists"); throw new SqliteRepositoryError("Authorized Research snapshot write failed", "authorized_research.snapshot.insert"); } return Promise.resolve(); }
  public listMissionsByWorkspaceId(workspaceId: string, limit: number): Promise<readonly AuthorizedResearchMission[]> { assertActiveTransaction(this.scope); assertId(workspaceId); assertLimit(limit); const rows = this.database.prepare("SELECT record_json FROM authorized_research_missions WHERE workspace_id = ? ORDER BY CASE status WHEN 'BLOCKED' THEN 0 WHEN 'RUNNING' THEN 1 ELSE 2 END, updated_at DESC, mission_id ASC LIMIT ?").all(workspaceId, limit); return Promise.resolve(Object.freeze(rows.map((row) => this.#decodeMission(row)))); }
  public listSnapshotsByMissionId(missionId: string): Promise<readonly ResearchAcquisitionSnapshot[]> { assertActiveTransaction(this.scope); assertId(missionId); const rows = this.database.prepare("SELECT record_json FROM research_acquisition_snapshots WHERE mission_id = ? ORDER BY acquired_at ASC, snapshot_id ASC").all(missionId); return Promise.resolve(Object.freeze(rows.map((row) => this.#decodeSnapshot(row)))); }
  public updateMission(mission: AuthorizedResearchMission, expectation: { readonly version: number }): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#checkedMission(mission); const current = this.#selectMission(checked.input.missionId); if (current?.version !== expectation.version || current.status !== "RUNNING" || checked.version !== expectation.version + 1 || !["BLOCKED", "READY"].includes(checked.status) || !sameMissionIdentity(current, checked)) throw new RepositoryConflictError("Authorized Research Mission transition is invalid"); const result = this.database.prepare("UPDATE authorized_research_missions SET status = ?, version = ?, updated_at = ?, record_json = ? WHERE mission_id = ? AND version = ?").run(checked.status, checked.version, checked.updatedAt, JSON.stringify(checked), checked.input.missionId, expectation.version); if (result.changes !== 1) throw new RepositoryConflictError("Authorized Research Mission changed during update"); return Promise.resolve(); }
  #selectMission(missionId: string): AuthorizedResearchMission | undefined { const row = this.database.prepare("SELECT record_json FROM authorized_research_missions WHERE mission_id = ?").get(missionId); return row === undefined ? undefined : this.#decodeMission(row); }
  #decodeMission(row: Record<string, unknown>): AuthorizedResearchMission { if (typeof row.record_json !== "string") throw new RepositoryValidationError("Authorized Research Mission is corrupted"); try { return this.#checkedMission(JSON.parse(row.record_json)); } catch (error) { if (error instanceof RepositoryValidationError) throw error; throw new RepositoryValidationError("Authorized Research Mission is corrupted"); } }
  #decodeSnapshot(row: Record<string, unknown>): ResearchAcquisitionSnapshot { if (typeof row.record_json !== "string") throw new RepositoryValidationError("Authorized Research snapshot is corrupted"); try { return this.#checkedSnapshot(JSON.parse(row.record_json)); } catch (error) { if (error instanceof RepositoryValidationError) throw error; throw new RepositoryValidationError("Authorized Research snapshot is corrupted"); } }
  #checkedMission(value: unknown): AuthorizedResearchMission { const checked = this.#mission.validate(value); if (!checked.ok) throw new RepositoryValidationError("Authorized Research Mission is invalid", { issueCount: checked.issues.length }); return checked.value; }
  #checkedSnapshot(value: unknown): ResearchAcquisitionSnapshot { const checked = this.#snapshot.validate(value); if (!checked.ok) throw new RepositoryValidationError("Authorized Research snapshot is invalid", { issueCount: checked.issues.length }); return checked.value; }
}

function sameMissionIdentity(left: AuthorizedResearchMission, right: AuthorizedResearchMission): boolean { return left.actorId === right.actorId && left.createdAt === right.createdAt && left.inputFingerprint === right.inputFingerprint && left.input.missionId === right.input.missionId && left.workspaceId === right.workspaceId && JSON.stringify(left.input) === JSON.stringify(right.input); }
function assertId(value: unknown): asserts value is string { if (typeof value !== "string" || !/^[a-zA-Z0-9@._:-]{1,128}$/u.test(value)) throw new RepositoryValidationError("Authorized Research identifier is invalid"); }
function assertLimit(value: unknown): asserts value is number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > 100) throw new RepositoryValidationError("Authorized Research list limit is invalid"); }
