import type { DatabaseSync } from "node:sqlite";

import type { AgentCompanyWorkdayIdentity, AgentCompanyWorkdayRepository } from "../../agent-company/agent-company-workday-repository.js";
import type { AgentCompanyWorkday } from "../../agent-company/operational-agent-company.js";
import { AgentCompanyWorkdayValidator } from "../../agent-company/operational-agent-company-validator.js";
import { RepositoryConflictError, RepositoryValidationError } from "../../errors/core-error.js";
import { isSqliteConstraintError, SqliteRepositoryError } from "./sqlite-error.js";
import { assertActiveTransaction, type SqliteTransactionScope } from "./sqlite-transaction-scope.js";

export class SqliteAgentCompanyWorkdayRepository implements AgentCompanyWorkdayRepository {
  readonly #validator = new AgentCompanyWorkdayValidator();
  public constructor(private readonly database: DatabaseSync, private readonly scope: SqliteTransactionScope) {}
  public getByOwner(identity: AgentCompanyWorkdayIdentity, workdayId: string): Promise<AgentCompanyWorkday | undefined> { assertActiveTransaction(this.scope); assertIdentity(identity); assertId(workdayId); const row = this.database.prepare("SELECT record_json FROM agent_company_workdays WHERE workday_id = ? AND workspace_id = ? AND actor_id = ?").get(workdayId, identity.workspaceId, identity.actorId); if (row === undefined) return Promise.resolve(undefined); const record = this.#decode(row); if (record.workspaceId !== identity.workspaceId || record.actorId !== identity.actorId) throw new RepositoryValidationError("Agent Company owner-scoped read returned cross-identity data"); return Promise.resolve(record); }
  public insert(record: AgentCompanyWorkday): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#checked(record); if (checked.version !== 0) throw new RepositoryValidationError("A new Agent Company workday must start at version zero"); try { this.database.prepare("INSERT INTO agent_company_workdays (workday_id, workspace_id, actor_id, status, version, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?)").run(checked.workdayId, checked.workspaceId, checked.actorId, checked.status, checked.version, checked.updatedAt, JSON.stringify(checked)); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError("Agent Company workday already exists"); throw new SqliteRepositoryError("Agent Company workday write failed", "agent_company_workday.insert"); } return Promise.resolve(); }
  public listByOwner(identity: AgentCompanyWorkdayIdentity, limit: number): Promise<readonly AgentCompanyWorkday[]> { assertActiveTransaction(this.scope); assertIdentity(identity); assertLimit(limit); const rows = this.database.prepare("SELECT record_json FROM agent_company_workdays WHERE workspace_id = ? AND actor_id = ? ORDER BY CASE status WHEN 'BLOCKED' THEN 0 WHEN 'AWAITING_FABIO' THEN 1 ELSE 2 END, updated_at DESC, workday_id ASC LIMIT ?").all(identity.workspaceId, identity.actorId, limit); const records = rows.map((row) => this.#decode(row)); if (records.some((record) => record.workspaceId !== identity.workspaceId || record.actorId !== identity.actorId)) throw new RepositoryValidationError("Agent Company owner-scoped read returned cross-identity data"); return Promise.resolve(Object.freeze(records)); }
  public update(record: AgentCompanyWorkday, expectation: { readonly version: number }): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#checked(record); const identity = { actorId: checked.actorId, workspaceId: checked.workspaceId }; const current = this.#select(identity, checked.workdayId); if (current?.version !== expectation.version || checked.version !== expectation.version + 1 || !sameIdentity(current, checked) || !transitionAllowed(current, checked)) throw new RepositoryConflictError("Agent Company workday transition is invalid"); const result = this.database.prepare("UPDATE agent_company_workdays SET status = ?, version = ?, updated_at = ?, record_json = ? WHERE workday_id = ? AND workspace_id = ? AND actor_id = ? AND version = ?").run(checked.status, checked.version, checked.updatedAt, JSON.stringify(checked), checked.workdayId, checked.workspaceId, checked.actorId, expectation.version); if (result.changes !== 1) throw new RepositoryConflictError("Agent Company workday changed during update"); return Promise.resolve(); }
  #select(identity: AgentCompanyWorkdayIdentity, workdayId: string): AgentCompanyWorkday | undefined { const row = this.database.prepare("SELECT record_json FROM agent_company_workdays WHERE workday_id = ? AND workspace_id = ? AND actor_id = ?").get(workdayId, identity.workspaceId, identity.actorId); return row === undefined ? undefined : this.#decode(row); }
  #decode(row: Record<string, unknown>): AgentCompanyWorkday { if (typeof row.record_json !== "string") throw new RepositoryValidationError("Agent Company workday is corrupted"); try { return this.#checked(JSON.parse(row.record_json)); } catch (error) { if (error instanceof RepositoryValidationError) throw error; throw new RepositoryValidationError("Agent Company workday is corrupted"); } }
  #checked(value: unknown): AgentCompanyWorkday { const result = this.#validator.validate(value); if (!result.ok) throw new RepositoryValidationError("Agent Company workday is invalid", { issueCount: result.issues.length }); return result.value; }
}

function transitionAllowed(previous: AgentCompanyWorkday, next: AgentCompanyWorkday): boolean { if (previous.status !== "RUNNING" || !["RUNNING", "BLOCKED", "AWAITING_FABIO"].includes(next.status)) return false; const changed = next.tasks.filter((task, index) => JSON.stringify(task) !== JSON.stringify(previous.tasks[index])); return changed.length <= 1 || (changed.length === 0 && next.status === "AWAITING_FABIO"); }
function sameIdentity(left: AgentCompanyWorkday, right: AgentCompanyWorkday): boolean { return left.actorId === right.actorId && left.createdAt === right.createdAt && left.inputFingerprint === right.inputFingerprint && left.workdayId === right.workdayId && left.workspaceId === right.workspaceId && JSON.stringify(left.input) === JSON.stringify(right.input); }
function assertId(value: unknown): asserts value is string { if (typeof value !== "string" || !/^[a-zA-Z0-9@._:-]{1,128}$/u.test(value)) throw new RepositoryValidationError("Agent Company identifier is invalid"); }
function assertIdentity(identity: AgentCompanyWorkdayIdentity): void { assertId(identity.actorId); assertId(identity.workspaceId); }
function assertLimit(value: unknown): asserts value is number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > 100) throw new RepositoryValidationError("Agent Company list limit is invalid"); }
