import type { DatabaseSync } from "node:sqlite";

import { RepositoryConflictError, RepositoryValidationError } from "../../errors/core-error.js";
import { isProductionRuntimeJobTransitionAllowed, type ProductionRuntimeJob } from "../../production-runtime/production-runtime-job.js";
import type { ProductionRuntimeJobCounts, ProductionRuntimeJobRepository, ProductionRuntimeJobUpdateExpectation } from "../../production-runtime/production-runtime-job-repository.js";
import { ProductionRuntimeJobValidator } from "../../production-runtime/production-runtime-validator.js";
import { isSqliteConstraintError, SqliteRepositoryError } from "./sqlite-error.js";
import { assertActiveTransaction, type SqliteTransactionScope } from "./sqlite-transaction-scope.js";

export class SqliteProductionRuntimeJobRepository implements ProductionRuntimeJobRepository {
  readonly #validator = new ProductionRuntimeJobValidator();
  public constructor(private readonly database: DatabaseSync, private readonly scope: SqliteTransactionScope) {}

  public claimNextDue(workspaceId: string, now: string, leaseExpiresAt: string): Promise<ProductionRuntimeJob | undefined> {
    assertActiveTransaction(this.scope);
    assertId(workspaceId); assertTimestamp(now); assertTimestamp(leaseExpiresAt);
    const row = this.database.prepare("SELECT record_json FROM production_runtime_jobs WHERE workspace_id = ? AND status IN ('QUEUED', 'RETRY_SCHEDULED') AND run_after <= ? ORDER BY run_after ASC, job_id ASC LIMIT 1").get(workspaceId, now);
    if (row === undefined) return Promise.resolve(undefined);
    if (typeof row.record_json !== "string") throw new RepositoryValidationError("Production Runtime job is corrupted");
    const current = this.#decode(row.record_json);
    const next = this.#validate(claimed(current, now, leaseExpiresAt));
    const result = this.database.prepare("UPDATE production_runtime_jobs SET status = ?, version = ?, run_after = ?, lease_expires_at = ?, updated_at = ?, record_json = ? WHERE job_id = ? AND version = ?").run(next.status, next.version, next.runAfter, next.leaseExpiresAt ?? null, next.updatedAt, JSON.stringify(next), next.jobId, current.version);
    if (result.changes !== 1) throw new RepositoryConflictError("Production Runtime job changed during claim", { jobId: current.jobId });
    return Promise.resolve(next);
  }
  public getById(jobId: string): Promise<ProductionRuntimeJob | undefined> { assertActiveTransaction(this.scope); assertId(jobId); const row = this.database.prepare("SELECT record_json FROM production_runtime_jobs WHERE job_id = ?").get(jobId); if (row === undefined) return Promise.resolve(undefined); if (typeof row.record_json !== "string") throw new RepositoryValidationError("Production Runtime job is corrupted"); return Promise.resolve(this.#decode(row.record_json)); }
  public insert(job: ProductionRuntimeJob): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#validate(job); if (checked.version !== 0 || checked.status !== "QUEUED") throw new RepositoryValidationError("A new Production Runtime job must be queued at version zero"); try { this.database.prepare("INSERT INTO production_runtime_jobs (job_id, workspace_id, actor_id, status, version, run_after, lease_expires_at, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)").run(checked.jobId, checked.workspaceId, checked.actorId, checked.status, checked.version, checked.runAfter, null, checked.updatedAt, JSON.stringify(checked)); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError("Production Runtime job already exists", { jobId: checked.jobId }); throw new SqliteRepositoryError("Production Runtime job write failed", "production_runtime_job.insert"); } return Promise.resolve(); }
  public listExpiredClaims(workspaceId: string, now: string, limit: number): Promise<readonly ProductionRuntimeJob[]> { assertActiveTransaction(this.scope); assertId(workspaceId); assertTimestamp(now); if (!Number.isSafeInteger(limit) || limit < 1 || limit > 25) throw new RepositoryValidationError("Production Runtime expiry limit is invalid"); const rows = this.database.prepare("SELECT record_json FROM production_runtime_jobs WHERE workspace_id = ? AND status = 'RUNNING' AND lease_expires_at <= ? ORDER BY lease_expires_at ASC, job_id ASC LIMIT ?").all(workspaceId, now, limit); return Promise.resolve(Object.freeze(rows.map((row) => { if (typeof row.record_json !== "string") throw new RepositoryValidationError("Production Runtime job is corrupted"); return this.#decode(row.record_json); }))); }
  public summarize(workspaceId: string): Promise<ProductionRuntimeJobCounts> { assertActiveTransaction(this.scope); assertId(workspaceId); const rows = this.database.prepare("SELECT status, COUNT(*) AS count FROM production_runtime_jobs WHERE workspace_id = ? GROUP BY status").all(workspaceId); const counts: Record<ProductionRuntimeJob["status"], number> = { COMPLETED: 0, DEAD_LETTER: 0, QUEUED: 0, RETRY_SCHEDULED: 0, RUNNING: 0 }; for (const row of rows) { const count = row.count; if (typeof row.status !== "string" || typeof count !== "number" || !Number.isSafeInteger(count) || !(row.status in counts)) throw new RepositoryValidationError("Production Runtime job summary is corrupted"); counts[row.status as ProductionRuntimeJob["status"]] = count; } return Promise.resolve(Object.freeze({ completed: counts.COMPLETED, deadLetter: counts.DEAD_LETTER, queued: counts.QUEUED, retryScheduled: counts.RETRY_SCHEDULED, running: counts.RUNNING })); }
  public update(job: ProductionRuntimeJob, expectation: ProductionRuntimeJobUpdateExpectation): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#validate(job); if (!Number.isSafeInteger(expectation.version) || expectation.version < 0) throw new RepositoryValidationError("Production Runtime update expectation is invalid"); const current = this.#select(checked.jobId); if (current === undefined) throw new RepositoryConflictError("Production Runtime job does not exist", { jobId: checked.jobId }); if (current.version !== expectation.version || checked.version !== expectation.version + 1) throw new RepositoryConflictError("Production Runtime job changed after read", { actualVersion: current.version, expectedVersion: expectation.version, jobId: checked.jobId }); if (!sameIdentity(current, checked) || !transition(current, checked)) throw new RepositoryConflictError("Production Runtime job transition is invalid", { jobId: checked.jobId }); const result = this.database.prepare("UPDATE production_runtime_jobs SET status = ?, version = ?, run_after = ?, lease_expires_at = ?, updated_at = ?, record_json = ? WHERE job_id = ? AND version = ?").run(checked.status, checked.version, checked.runAfter, checked.leaseExpiresAt ?? null, checked.updatedAt, JSON.stringify(checked), checked.jobId, expectation.version); if (result.changes !== 1) throw new RepositoryConflictError("Production Runtime job changed during update", { jobId: checked.jobId }); return Promise.resolve(); }
  #select(jobId: string): ProductionRuntimeJob | undefined { const row = this.database.prepare("SELECT record_json FROM production_runtime_jobs WHERE job_id = ?").get(jobId); if (row === undefined) return undefined; if (typeof row.record_json !== "string") throw new RepositoryValidationError("Production Runtime job is corrupted"); return this.#decode(row.record_json); }
  #decode(value: string): ProductionRuntimeJob { try { return this.#validate(JSON.parse(value)); } catch (error) { if (error instanceof RepositoryValidationError) throw error; throw new RepositoryValidationError("Production Runtime job is corrupted"); } }
  #validate(value: unknown): ProductionRuntimeJob { const checked = this.#validator.validate(value); if (!checked.ok) throw new RepositoryValidationError("Production Runtime job is invalid", { issueCount: checked.issues.length }); return checked.value; }
}

function transition(previous: ProductionRuntimeJob, next: ProductionRuntimeJob): boolean { return isProductionRuntimeJobTransitionAllowed(previous.status, next.status) && (next.status === "RUNNING" ? next.attempt === previous.attempt + 1 : next.attempt === previous.attempt); }
function sameIdentity(previous: ProductionRuntimeJob, next: ProductionRuntimeJob): boolean { return previous.actorId === next.actorId && previous.createdAt === next.createdAt && previous.jobId === next.jobId && previous.maxAttempts === next.maxAttempts && previous.workspaceId === next.workspaceId && JSON.stringify(previous.brief) === JSON.stringify(next.brief); }
function claimed(current: ProductionRuntimeJob, updatedAt: string, leaseExpiresAt: string): ProductionRuntimeJob { return { actorId: current.actorId, attempt: current.attempt + 1, brief: current.brief, contractVersion: current.contractVersion, createdAt: current.createdAt, jobId: current.jobId, leaseExpiresAt, maxAttempts: current.maxAttempts, runAfter: current.runAfter, status: "RUNNING", updatedAt, version: current.version + 1, workspaceId: current.workspaceId }; }
function assertId(value: unknown): asserts value is string { if (typeof value !== "string" || !/^[a-z0-9][a-z0-9@._-]{0,127}$/u.test(value)) throw new RepositoryValidationError("Production Runtime ID is invalid"); }
function assertTimestamp(value: unknown): asserts value is string { if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/u.test(value)) throw new RepositoryValidationError("Production Runtime timestamp is invalid"); }
