import type { DatabaseSync } from "node:sqlite";

import { RepositoryConflictError, RepositoryValidationError } from "../../errors/core-error.js";
import type { OperationsControlRepository } from "../../operations-control/operations-control-repository.js";
import type { ControlActionProposal, ControlActionReceipt, OperationsIncidentRecord, ProductionControlRecord } from "../../operations-control/operations-control.js";
import { ControlActionProposalValidator, ControlActionReceiptValidator, OperationsIncidentRecordValidator, ProductionControlRecordValidator, controlFingerprint } from "../../operations-control/operations-control-validator.js";
import { isSqliteConstraintError, SqliteRepositoryError } from "./sqlite-error.js";
import { assertActiveTransaction, type SqliteTransactionScope } from "./sqlite-transaction-scope.js";

export class SqliteOperationsControlRepository implements OperationsControlRepository {
  readonly #incidentValidator = new OperationsIncidentRecordValidator();
  readonly #productionValidator = new ProductionControlRecordValidator();
  readonly #proposalValidator = new ControlActionProposalValidator();
  readonly #receiptValidator = new ControlActionReceiptValidator();

  public constructor(private readonly database: DatabaseSync, private readonly scope: SqliteTransactionScope) {}

  public getIncident(incidentId: string): Promise<OperationsIncidentRecord | undefined> { assertActiveTransaction(this.scope); assertId(incidentId); const row = this.database.prepare("SELECT record_json FROM operations_incidents WHERE incident_id = ?").get(incidentId); return Promise.resolve(row === undefined ? undefined : this.#decodeIncident(row)); }
  public getProductionControl(productionId: string): Promise<ProductionControlRecord | undefined> { assertActiveTransaction(this.scope); assertId(productionId); const row = this.database.prepare("SELECT record_json FROM production_controls WHERE production_id = ?").get(productionId); return Promise.resolve(row === undefined ? undefined : this.#decodeProduction(row)); }
  public getProposal(proposalId: string): Promise<ControlActionProposal | undefined> { assertActiveTransaction(this.scope); assertId(proposalId); const row = this.database.prepare("SELECT record_json FROM control_action_proposals WHERE proposal_id = ?").get(proposalId); return Promise.resolve(row === undefined ? undefined : this.#decodeProposal(row)); }
  public getProposalByIdempotencyKey(workspaceId: string, idempotencyKey: string): Promise<ControlActionProposal | undefined> { assertActiveTransaction(this.scope); assertId(workspaceId); assertId(idempotencyKey); const row = this.database.prepare("SELECT record_json FROM control_action_proposals WHERE workspace_id = ? AND idempotency_key = ?").get(workspaceId, idempotencyKey); return Promise.resolve(row === undefined ? undefined : this.#decodeProposal(row)); }
  public getReceiptByIdempotencyKey(workspaceId: string, idempotencyKey: string): Promise<ControlActionReceipt | undefined> { assertActiveTransaction(this.scope); assertId(workspaceId); assertId(idempotencyKey); const row = this.database.prepare("SELECT record_json FROM control_action_receipts WHERE workspace_id = ? AND idempotency_key = ?").get(workspaceId, idempotencyKey); return Promise.resolve(row === undefined ? undefined : this.#decodeReceipt(row)); }

  public insertIncident(record: OperationsIncidentRecord): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#incident(record); if (checked.version !== 0 || checked.status !== "OPEN" || checked.fingerprint !== incidentFingerprint(checked)) throw new RepositoryValidationError("New Operations incident must be open at version zero with a valid fingerprint"); this.#insert("INSERT INTO operations_incidents (incident_id, workspace_id, actor_id, status, severity, version, updated_at, fingerprint, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [checked.incidentId, checked.workspaceId, checked.actorId, checked.status, checked.severity, checked.version, checked.updatedAt, checked.fingerprint, JSON.stringify(checked)], "Operations incident", "operations_incident.insert"); return Promise.resolve(); }
  public insertProductionControl(record: ProductionControlRecord): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#production(record); if (checked.version !== 0 || checked.state !== "ACTIVE" || checked.createdAt !== checked.updatedAt || checked.history.length !== 0 || checked.revisions.length !== 0) throw new RepositoryValidationError("New production control must be active and empty at version zero"); this.#insert("INSERT INTO production_controls (production_id, workspace_id, actor_id, state, source_production_version, source_package_fingerprint, version, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", [checked.productionId, checked.workspaceId, checked.actorId, checked.state, checked.sourceProductionVersion, checked.sourcePackageFingerprint, checked.version, checked.updatedAt, JSON.stringify(checked)], "Production control", "production_control.insert"); return Promise.resolve(); }
  public insertProposal(proposal: ControlActionProposal): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#proposal(proposal); if (checked.version !== 0 || checked.state !== "PENDING") throw new RepositoryValidationError("New control action proposal must be pending at version zero"); this.#insert("INSERT INTO control_action_proposals (proposal_id, workspace_id, actor_id, action, state, expires_at, idempotency_key, version, updated_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", [checked.proposalId, checked.workspaceId, checked.actorId, checked.action, checked.state, checked.expiresAt, checked.idempotencyKey, checked.version, checked.updatedAt, JSON.stringify(checked)], "Control action proposal", "control_action_proposal.insert"); return Promise.resolve(); }
  public insertReceipt(receipt: ControlActionReceipt): Promise<void> { assertActiveTransaction(this.scope); const checked = this.#receipt(receipt); if (checked.outcomeFingerprint !== receiptFingerprint(checked)) throw new RepositoryValidationError("Control action receipt fingerprint is invalid"); this.#insert("INSERT INTO control_action_receipts (receipt_id, proposal_id, workspace_id, actor_id, action, idempotency_key, recorded_at, record_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?)", [checked.receiptId, checked.proposalId, checked.workspaceId, checked.actorId, checked.action, checked.idempotencyKey, checked.recordedAt, JSON.stringify(checked)], "Control action receipt", "control_action_receipt.insert"); return Promise.resolve(); }

  public listIncidents(workspaceId: string, limit: number): Promise<readonly OperationsIncidentRecord[]> { return this.#list("SELECT record_json FROM operations_incidents WHERE workspace_id = ? ORDER BY CASE status WHEN 'OPEN' THEN 0 ELSE 1 END, updated_at DESC, incident_id ASC LIMIT ?", workspaceId, limit, (row) => this.#decodeIncident(row)); }
  public listProductionControls(workspaceId: string, limit: number): Promise<readonly ProductionControlRecord[]> { return this.#list("SELECT record_json FROM production_controls WHERE workspace_id = ? ORDER BY updated_at DESC, production_id ASC LIMIT ?", workspaceId, limit, (row) => this.#decodeProduction(row)); }
  public listReceipts(workspaceId: string, limit: number): Promise<readonly ControlActionReceipt[]> { return this.#list("SELECT record_json FROM control_action_receipts WHERE workspace_id = ? ORDER BY recorded_at DESC, receipt_id ASC LIMIT ?", workspaceId, limit, (row) => this.#decodeReceipt(row)); }

  public updateIncident(record: OperationsIncidentRecord, expectation: { readonly version: number }): Promise<void> {
    assertActiveTransaction(this.scope); const checked = this.#incident(record); const current = this.#selectIncident(checked.incidentId);
    if (current?.version !== expectation.version || checked.version !== expectation.version + 1 || !sameIncidentIdentity(current, checked) || current.status !== "OPEN" || checked.status !== "ACKNOWLEDGED" || checked.fingerprint !== incidentFingerprint(checked)) throw new RepositoryConflictError("Operations incident transition is invalid");
    const result = this.database.prepare("UPDATE operations_incidents SET status = ?, version = ?, updated_at = ?, fingerprint = ?, record_json = ? WHERE incident_id = ? AND version = ?").run(checked.status, checked.version, checked.updatedAt, checked.fingerprint, JSON.stringify(checked), checked.incidentId, expectation.version); assertChanged(result.changes, "Operations incident"); return Promise.resolve();
  }

  public updateProductionControl(record: ProductionControlRecord, expectation: { readonly version: number }): Promise<void> {
    assertActiveTransaction(this.scope); const checked = this.#production(record); const current = this.#selectProduction(checked.productionId);
    if (current?.version !== expectation.version || checked.version !== expectation.version + 1 || !sameProductionIdentity(current, checked) || !productionControlTransition(current, checked)) throw new RepositoryConflictError("Production control transition is invalid");
    const result = this.database.prepare("UPDATE production_controls SET state = ?, version = ?, updated_at = ?, record_json = ? WHERE production_id = ? AND version = ?").run(checked.state, checked.version, checked.updatedAt, JSON.stringify(checked), checked.productionId, expectation.version); assertChanged(result.changes, "Production control"); return Promise.resolve();
  }

  public updateProposal(proposal: ControlActionProposal, expectation: { readonly version: number }): Promise<void> {
    assertActiveTransaction(this.scope); const checked = this.#proposal(proposal); const current = this.#selectProposal(checked.proposalId);
    if (current?.version !== expectation.version || checked.version !== expectation.version + 1 || !sameProposalCore(current, checked) || !proposalTransition(current, checked)) throw new RepositoryConflictError("Control action proposal transition is invalid");
    const result = this.database.prepare("UPDATE control_action_proposals SET state = ?, expires_at = ?, version = ?, updated_at = ?, record_json = ? WHERE proposal_id = ? AND version = ?").run(checked.state, checked.expiresAt, checked.version, checked.updatedAt, JSON.stringify(checked), checked.proposalId, expectation.version); assertChanged(result.changes, "Control action proposal"); return Promise.resolve();
  }

  #insert(sql: string, values: readonly (number | string)[], label: string, operation: string): void { try { this.database.prepare(sql).run(...values); } catch (error) { if (isSqliteConstraintError(error)) throw new RepositoryConflictError(`${label} already exists`); throw new SqliteRepositoryError(`${label} write failed`, operation); } }
  #list<T>(sql: string, workspaceId: string, limit: number, decode: (row: Readonly<Record<string, unknown>>) => T): Promise<readonly T[]> { assertActiveTransaction(this.scope); assertId(workspaceId); assertLimit(limit); return Promise.resolve(Object.freeze(this.database.prepare(sql).all(workspaceId, limit).map(decode))); }
  #selectIncident(id: string): OperationsIncidentRecord | undefined { const row = this.database.prepare("SELECT record_json FROM operations_incidents WHERE incident_id = ?").get(id); return row === undefined ? undefined : this.#decodeIncident(row); }
  #selectProduction(id: string): ProductionControlRecord | undefined { const row = this.database.prepare("SELECT record_json FROM production_controls WHERE production_id = ?").get(id); return row === undefined ? undefined : this.#decodeProduction(row); }
  #selectProposal(id: string): ControlActionProposal | undefined { const row = this.database.prepare("SELECT record_json FROM control_action_proposals WHERE proposal_id = ?").get(id); return row === undefined ? undefined : this.#decodeProposal(row); }
  #decodeIncident(row: Readonly<Record<string, unknown>>): OperationsIncidentRecord { return this.#decode(row, (value) => this.#incident(value), "Operations incident"); }
  #decodeProduction(row: Readonly<Record<string, unknown>>): ProductionControlRecord { return this.#decode(row, (value) => this.#production(value), "Production control"); }
  #decodeProposal(row: Readonly<Record<string, unknown>>): ControlActionProposal { return this.#decode(row, (value) => this.#proposal(value), "Control action proposal"); }
  #decodeReceipt(row: Readonly<Record<string, unknown>>): ControlActionReceipt { return this.#decode(row, (value) => this.#receipt(value), "Control action receipt"); }
  #decode<T>(row: Readonly<Record<string, unknown>>, validate: (value: unknown) => T, label: string): T { if (typeof row.record_json !== "string") throw new RepositoryValidationError(`${label} is corrupted`); try { return validate(JSON.parse(row.record_json)); } catch (error) { if (error instanceof RepositoryValidationError) throw error; throw new RepositoryValidationError(`${label} is corrupted`); } }
  #incident(value: unknown): OperationsIncidentRecord { return validated(value, this.#incidentValidator, "Operations incident"); }
  #production(value: unknown): ProductionControlRecord { return validated(value, this.#productionValidator, "Production control"); }
  #proposal(value: unknown): ControlActionProposal { return validated(value, this.#proposalValidator, "Control action proposal"); }
  #receipt(value: unknown): ControlActionReceipt { return validated(value, this.#receiptValidator, "Control action receipt"); }
}

function validated<T>(value: unknown, validator: { validate(value: unknown): { readonly ok: true; readonly value: T } | { readonly ok: false; readonly issues: readonly unknown[] } }, label: string): T { const result = validator.validate(value); if (!result.ok) throw new RepositoryValidationError(`${label} is invalid`, { issueCount: result.issues.length }); return result.value; }
function sameIncidentIdentity(left: OperationsIncidentRecord, right: OperationsIncidentRecord): boolean { return left.incidentId === right.incidentId && left.workspaceId === right.workspaceId && left.actorId === right.actorId && left.createdAt === right.createdAt && left.severity === right.severity && left.summaryCode === right.summaryCode; }
function sameProductionIdentity(left: ProductionControlRecord, right: ProductionControlRecord): boolean { return left.productionId === right.productionId && left.workspaceId === right.workspaceId && left.actorId === right.actorId && left.createdAt === right.createdAt && left.sourcePackageFingerprint === right.sourcePackageFingerprint && left.sourceProductionVersion === right.sourceProductionVersion; }
function sameProposalCore(left: ControlActionProposal, right: ControlActionProposal): boolean { return left.proposalId === right.proposalId && left.workspaceId === right.workspaceId && left.actorId === right.actorId && left.action === right.action && left.createdAt === right.createdAt && left.idempotencyKey === right.idempotencyKey && JSON.stringify(left.target) === JSON.stringify(right.target) && JSON.stringify(left.reason) === JSON.stringify(right.reason) && JSON.stringify(left.revision) === JSON.stringify(right.revision); }
function proposalTransition(previous: ControlActionProposal, next: ControlActionProposal): boolean {
  if (Date.parse(next.updatedAt) < Date.parse(previous.updatedAt)) return false;
  if (previous.state === "PENDING" && (next.state === "CONSUMED" || next.state === "EXPIRED")) return previous.confirmationTokenHash === next.confirmationTokenHash && previous.expiresAt === next.expiresAt;
  if ((previous.state === "PENDING" || previous.state === "EXPIRED") && next.state === "PENDING") return previous.confirmationTokenHash !== next.confirmationTokenHash && Date.parse(next.expiresAt) > Date.parse(next.updatedAt);
  return false;
}
function productionControlTransition(previous: ProductionControlRecord, next: ProductionControlRecord): boolean {
  const entry = next.history.at(-1);
  if (entry === undefined || next.history.length !== previous.history.length + 1 || JSON.stringify(next.history.slice(0, -1)) !== JSON.stringify(previous.history) || JSON.stringify(next.revisions.slice(0, previous.revisions.length)) !== JSON.stringify(previous.revisions) || next.revisions.length > previous.revisions.length + 1 || entry.actorId !== next.actorId || entry.occurredAt !== next.updatedAt || entry.state !== next.state || entry.version !== next.version) return false;
  if (previous.state === "ACTIVE" && next.state === "PAUSED") return entry.action === "PAUSE" && next.revisions.length === previous.revisions.length;
  if (previous.state === "PAUSED" && next.state === "ACTIVE") return entry.action === "RESUME" && next.revisions.length === previous.revisions.length;
  if ((previous.state === "ACTIVE" || previous.state === "PAUSED") && next.state === "CANCELLED") return entry.action === "CANCEL" && next.revisions.length === previous.revisions.length;
  if ((previous.state === "ACTIVE" || previous.state === "PAUSED") && next.state === "REVISION_REQUIRED") {
    const revision = next.revisions.at(-1);
    return entry.action === "REQUEST_REVISION" && next.revisions.length === previous.revisions.length + 1 && revision?.sourcePackageFingerprint === next.sourcePackageFingerprint && revision.sourceProductionVersion === next.sourceProductionVersion;
  }
  return false;
}
function incidentFingerprint(record: OperationsIncidentRecord): string { return controlFingerprint({ ...(record.acknowledgedAt === undefined ? {} : { acknowledgedAt: record.acknowledgedAt }), ...(record.acknowledgedBy === undefined ? {} : { acknowledgedBy: record.acknowledgedBy }), actorId: record.actorId, contractVersion: record.contractVersion, createdAt: record.createdAt, incidentId: record.incidentId, severity: record.severity, status: record.status, summaryCode: record.summaryCode, updatedAt: record.updatedAt, version: record.version, workspaceId: record.workspaceId }); }
function receiptFingerprint(receipt: ControlActionReceipt): string { return controlFingerprint({ action: receipt.action, actorId: receipt.actorId, contractVersion: receipt.contractVersion, idempotencyKey: receipt.idempotencyKey, proposalId: receipt.proposalId, receiptId: receipt.receiptId, recordedAt: receipt.recordedAt, resultEntityId: receipt.resultEntityId, resultEntityVersion: receipt.resultEntityVersion, target: receipt.target, workspaceId: receipt.workspaceId }); }
function assertChanged(value: number | bigint, label: string): void { if (value !== 1 && value !== 1n) throw new RepositoryConflictError(`${label} changed during update`); }
function assertId(value: unknown): asserts value is string { if (typeof value !== "string" || !/^[A-Za-z0-9][A-Za-z0-9@._:-]{0,191}$/u.test(value)) throw new RepositoryValidationError("Operations control identifier is invalid"); }
function assertLimit(value: unknown): asserts value is number { if (!Number.isSafeInteger(value) || (value as number) < 1 || (value as number) > 250) throw new RepositoryValidationError("Operations control list limit is invalid"); }
